#!/usr/bin/php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
    require __DIR__.'/vendor/autoload.php';
} else {
    require __DIR__.'/../../autoload.php';
}

$helper = new Meat\EnvoyHelper\EnvoyHelper();
$helper->loadEnv();
$helper->start();